name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install libasound2-dev libxkbcommon-dev libwayland-cursor0 libwayland-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
